# -*- coding: utf-8 -*-
"""模組化示範說明.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ylgYBCL7PJ9v-U3_aJ0fTtjomUUgEBG-
"""

!git clone https://github.com/oreilly-japan/deep-learning-from-scratch.git

ls

cd deep-learning-from-scratch

ls

cd ch06/

ls

!python batch_norm_test.py